# Generated by Django 4.2.29 on 2026-09-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=500)),
                ('budget', models.CharField(blank=True, default='₹50,00,000', max_length=100)),
                ('start_date', models.CharField(blank=True, default='', max_length=20)),
                ('target_date', models.CharField(blank=True, default='', max_length=20)),
                ('stage', models.CharField(blank=True, default='Planning', max_length=300)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_projects', to=settings.AUTH_USER_MODEL)),
                ('site_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-id'],
            },
        ),
    ]
