# Generated by Django 4.2.29 on 2026-09-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('stage', models.CharField(default='General Construction', max_length=100)),
                ('work_completed', models.TextField()),
                ('progress_added', models.IntegerField(default=0)),
                ('labor_count', models.IntegerField(default=0)),
                ('materials_used', models.TextField(blank=True, default='As per standard BOM')),
                ('weather', models.CharField(default='Clear / Sunny', max_length=100)),
                ('issues_delay', models.TextField(blank=True, default='None')),
                ('site_photos', models.TextField(blank=True, default='')),
                ('sub_tasks', models.JSONField(blank=True, default=list)),
                ('labor_breakdown', models.JSONField(blank=True, default=dict)),
                ('materials_breakdown', models.JSONField(blank=True, default=dict)),
                ('quality_checks', models.JSONField(blank=True, default=dict)),
                ('inspection_status', models.CharField(default='Verified', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project')),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
