# Generated by Django 4.2.29 on 2026-09-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_address', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=100)),
                ('building_type', models.CharField(max_length=100)),
                ('required_details', models.TextField(blank=True, default='')),
                ('target_user_id', models.IntegerField(blank=True, null=True)),
                ('target_role', models.CharField(default='contractor', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('assigned_engineer_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_requests',
                'ordering': ['-id'],
            },
        ),
    ]
